### ISSUE TITLE
Redirection to the destination path doesn’t work

### ISSUE THREAD

**Issue by motionVector** [mike-anthony/ProcessJumplinks#8] opened 2015-04-21 10:14 UTC
Redirection to the destination path doesn’t work, although debug mode signals that everything should work as intended. I still get just the 404 page not found with debug mode off again.
```
Page not found; scanning for jumplinks...
- Checked at: Tue, 21 Apr 2015 10:34:56 +0200
- Requested URL: http://visum4you.dev/visainfo/russland
- PW Version: 2.5.27

== START ==

[Checking jumplink #1]
- Timed Activation:             Sun, 12 Apr 2015 00:04:00 +0200 to Wed, 30 Nov -001 00:00:00 +0100 
- Original Source Path:         visainfo/{country:all}
- Compiled Source Path:         visainfo/(.*)
- Original Destination Path:    visum/{country}/
- Compiled Destination Path:    http://visum4you.dev/visum/russland/

Match found! We'll do the following redirect (302, temporary) when Debug Mode has been turned off:

- From URL:   http://visum4you.dev/visainfo/russland
- To URL:     http://visum4you.dev/visum/russland/
- Timed:      From Sun, 12 Apr 2015 00:04:00 +0200 onwards
```
Any Idea what could be the problem? Thanks!

**Comment by mike-anthony** [comment] 2015-04-21 12:55
I'm unable to reproduce this on my side - the redirect is working as intended. Is there any chance you could do a screen-cast to show me what's happening?

**Comment by joshuagatcke** [comment] 2015-04-24 19:03
I am also having this problem. Exactly as described.

**Comment by motionVector** [comment] 2015-04-24 21:01
The destination page exists. The URL never changes to the destination URL. There wouldn’t be much to show in a screencast.

**Comment by mike-anthony** [comment] 2015-04-25 04:52
And what happens when you turn of timed activation?

**Comment by mike-anthony** [comment] 2015-04-25 05:00
Okay, this is the culprit:

```php
$activated = ($starts || $ends)
	? ($time >= $starts && $time <= $ends)
	: true;
```

Whilst that's correct, the end time is not being calculated correctly (`Wed, 30 Nov -001 00:00:00 +0100`).

Will look into this shortly.

**Comment by mike-anthony** [comment] 2015-04-25 05:06
I find this to be quite interesting because the timestamps are indeed being set:

```php
if ($ends && !$starts) {
	$starts = time();
}

// If it starts (which it will always do), but doesn't end,
// then set a dummy timestamp that is always in the future.
if ($starts && !$ends) {
	$ends = time() + (60 * 60);
	$message = '(has no ending, using dummy timestamp)';
} else {
	$message = '';
}
```

So the only thing that could be going wrong is with the submission of the jumplink to the database.

Please could you show me what end time is shown in the editor for the jumplink in question? If the end time is empty, please could you tell me what it shows in your database? For reference, it should be this:

```
date_start: 2015-04-12 04:00:00
date_end: 0000-00-00 00:00:00
```

**Comment by mike-anthony** [comment] 2015-04-25 06:39
It should contain something other than the above, as my scan long outputs the following:

```
[Checking jumplink #9]
- Timed Activation:             Sun, 12 Apr 2015 04:00:00 +0200 to Sat, 25 Apr 2015 09:37:32 +0200 (has no ending, using dummy timestamp)
- Original Source Path:         visainfo/{country:all}
- Compiled Source Path:         visainfo/(.*)
- Original Destination Path:    visum/{country}/
- Compiled Destination Path:    http://processwire.dev.local/visum/z/
```

**Comment by mike-anthony** [comment] 2015-04-27 08:02
Have synced a fix to the dev branch (as above). Please let me know if the issue is resolved.

**Comment by motionVector** [comment] 2015-04-27 13:02
I was away for the weekend and couldn’t answer. I’ll try your fix later today. Thanks!

**Comment by mike-anthony** [comment] 2015-04-27 13:05
Not a problem at all :+1:

**Comment by mike-anthony** [comment] 2015-04-28 17:36
This appears to be fixed now. Closing this issue.

If you're still having problems, please feel free to re-open it.

**Closed by mike-anthony** 2015-04-28 17:36 UTC
Labels: Bug, Pending Confirmation

**Comment by motionVector** [comment] 2015-04-28 18:35
Thank you! You fixed it :) everything working as it should.
